### ISSUE TITLE
[BUG] CartLineQuantityAdjustButton overwrites attributes added by AddToCartButton

### ISSUE THREAD

**Issue by thedambar** [Shopify/hydrogen-react#119]
**Describe the bug**
When adding items to the shopping cart with AddToCartButton using attributes passed through the attributes prop, the attributes later appear to be overridden and removed if the quantity for that cart line is adjusted using CartLineQuantityAdjustButton.

**To Reproduce**

https://stackblitz.com/edit/shopify-hydrogen-n3hfqc

I have minimally modified this to pass attributes through the AddToCartButton in ProductForm.client.jsx, and to display any attributes in the CartLineItem.client.jsx.  To reproduce the bug, add an item to the shopping cart.  It should show the attribute 'Test: Testing' when you open the shopping cart.

Once the quantity is increased, the 'Test: Testing' attribute disappears.

**Expected behaviour**
I expected attributes to be retained unchanged when the quantity of the cart line item is adjusted.

**Screenshots**

**Comment by frehner** [comment]
We're now tracking this in #171
