### ISSUE TITLE
Choose a better name for `ShopifyAppSource`

### ISSUE THREAD

**Issue by jplhomer** [Shopify/hydrogen-react#139]
**Is your feature request related to a problem? Please describe.**
We currently define an enum called `ShopifyAppSource` to disambiguate between the Hydrogen and Custom Storefronts channel: https://github.com/Shopify/storefront-kit-react/blob/6184517a2bf2b62198f8601ff798d851b604d386/packages/react/src/analytics-constants.ts#L31

It's probably called this because it's literally referring to an "API Client ID" aka an internal app.

However, this is an internal concern and not a merchant- or dev-facing concern.

This is confusing, because it indicates to me that an "app" is somehow involved with me, an external-facing developer or merchant.

**Describe the solution you'd like**
Instead, we should call this something like `ShopifyChannelType`.

**Comment by jplhomer** [comment]
Idk, `vr` maybe?

other ideas: `ShopifySalesChannel` or `SalesChannelType`

**Comment by wizardlyhel** [comment]
I vote on `ShopifySalesChannel` .. and if in future it deviates ... we'll see when we cross that bridge
