### ISSUE TITLE
[Feature Request] Add support for `rich_text_field` metafield type in `parseMetafield`

### ISSUE THREAD

**Issue by DuncanFa** [Shopify/hydrogen-react#147]
**Is your feature request related to a problem? Please describe.**
Now that you can now create Rich Text metafields in the admin it would be great to be able to easily parse them using `parseMetafield` inside of React Storefront Kit. The `rich_text_field` type doesn't seem to be [currently supported](https://shopify.dev/api/hydrogen/utilities/parsemetafieldvalue#return-type)

**Describe the solution you'd like**
Recognizing the `rich_text_field` and translating the value to either an HTML string or React Nodes. 

**Describe alternatives you've considered**
I've created a utility based on experimenting with the JSON format but an official solution would probably be best when we deploy.

**Comment by frehner** [comment]
And here it is: Shopify/hydrogen#621 . I'm going to close this issue as a duplicate so that we can consolidate discussion in that issue, if that's ok. 

Thanks!
