### ISSUE TITLE
Storefront client warns about using a private token from server code

### ISSUE THREAD

**Issue by Nistrul** [Shopify/hydrogen-react#191]
**Describe the bug**
Storefront client incorrectly warns "You are attempting to use a private token in an environment where it can be easily accessed by anyone." when running from code on the server.

The cause
In packages/react/src/storefront-client.ts, line 50 the condition used to show the warning checks if globalThis is truthy instead of checking if globalThis.document is truthy. globalThis is defined on both servers and clients.

**To Reproduce**

1. npm create @shopify/hydrogen@latest
2. Demo Store
3. TypeScript
4. Install anywhere
5. Install dependencies with npm? No
6. cd projectDir
7. npx yarn
8. npx yarn dev

Using npm doesn't seem to trigger the warning as it seems to use the "default" module exports instead of the "developer" module exports. The default module exports (production exports) do not contain this warning.

**Expected behavior**
Code running on the server does not warn about using a private token.

**Comment by frehner** [comment]
Oh sorry, you meant this line:

https://github.com/Shopify/hydrogen-react/blob/35b1986ee14d49a3584350a50e98bb17d4f83295/packages/react/src/storefront-client.ts#L50

Yup that's wrong, good catch!

**Comment by frehner** [comment]
Released! https://github.com/Shopify/hydrogen-react/releases/tag/%40shopify%2Fhydrogen-react%402023.1.6
